# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/pitch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1281, 691))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 80))
        self.tabWidget.setIconSize(QtCore.QSize(25, 25))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 230, 371, 151))
        self.groupBox.setObjectName("groupBox")
        self.progressBarThrottle = QtWidgets.QProgressBar(self.groupBox)
        self.progressBarThrottle.setGeometry(QtCore.QRect(230, 30, 121, 23))
        self.progressBarThrottle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBarThrottle.setProperty("value", 76)
        self.progressBarThrottle.setObjectName("progressBarThrottle")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 30, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.progressBarYaw = QtWidgets.QProgressBar(self.groupBox)
        self.progressBarYaw.setGeometry(QtCore.QRect(230, 60, 121, 23))
        self.progressBarYaw.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBarYaw.setMinimum(-100)
        self.progressBarYaw.setProperty("value", 0)
        self.progressBarYaw.setObjectName("progressBarYaw")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.progressBarAUX = QtWidgets.QProgressBar(self.groupBox)
        self.progressBarAUX.setGeometry(QtCore.QRect(230, 90, 121, 23))
        self.progressBarAUX.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBarAUX.setProperty("value", 0)
        self.progressBarAUX.setObjectName("progressBarAUX")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(50, 90, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(50, 120, 91, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.progressBarAU = QtWidgets.QProgressBar(self.groupBox)
        self.progressBarAU.setGeometry(QtCore.QRect(230, 120, 121, 23))
        self.progressBarAU.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBarAU.setProperty("value", 100)
        self.progressBarAU.setObjectName("progressBarAU")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 371, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 181, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 181, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 181, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(220, 30, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(255, 0, 0)")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(220, 60, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(255, 0, 0)")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(220, 90, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:#FF0000")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_117 = QtWidgets.QLabel(self.groupBox_2)
        self.label_117.setGeometry(QtCore.QRect(220, 120, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_117.setFont(font)
        self.label_117.setStyleSheet("color:#FF0000")
        self.label_117.setAlignment(QtCore.Qt.AlignCenter)
        self.label_117.setObjectName("label_117")
        self.label_118 = QtWidgets.QLabel(self.groupBox_2)
        self.label_118.setGeometry(QtCore.QRect(10, 120, 181, 21))
        self.label_118.setAlignment(QtCore.Qt.AlignCenter)
        self.label_118.setObjectName("label_118")
        self.label_128 = QtWidgets.QLabel(self.groupBox_2)
        self.label_128.setGeometry(QtCore.QRect(10, 150, 181, 21))
        self.label_128.setAlignment(QtCore.Qt.AlignCenter)
        self.label_128.setObjectName("label_128")
        self.label_130 = QtWidgets.QLabel(self.groupBox_2)
        self.label_130.setGeometry(QtCore.QRect(220, 150, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_130.setFont(font)
        self.label_130.setStyleSheet("color:#FF0000")
        self.label_130.setAlignment(QtCore.Qt.AlignCenter)
        self.label_130.setObjectName("label_130")
        self.label_129 = QtWidgets.QLabel(self.groupBox_2)
        self.label_129.setGeometry(QtCore.QRect(10, 180, 181, 21))
        self.label_129.setAlignment(QtCore.Qt.AlignCenter)
        self.label_129.setObjectName("label_129")
        self.label_131 = QtWidgets.QLabel(self.groupBox_2)
        self.label_131.setGeometry(QtCore.QRect(220, 180, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_131.setFont(font)
        self.label_131.setStyleSheet("color:#FF0000")
        self.label_131.setAlignment(QtCore.Qt.AlignCenter)
        self.label_131.setObjectName("label_131")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(400, 20, 371, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(50, 30, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(220, 30, 141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:#FF0000")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(40, 60, 111, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(40, 90, 111, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(40, 120, 111, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(220, 60, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color:rgb(0, 170, 0)")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(220, 90, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color:rgb(0, 170, 0)")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(220, 120, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color:#FF0000")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(770, 10, 481, 611))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(10, 30, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.graphicsView = QOSM(self.groupBox_4)
        self.graphicsView.setGeometry(QtCore.QRect(10, 190, 471, 261))
        self.graphicsView.setObjectName("graphicsView")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(10, 170, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(30, 480, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(240, 480, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(20, 540, 151, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(240, 560, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(30, 560, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(30, 500, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(120, 480, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(340, 480, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(120, 560, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_4)
        self.label_30.setGeometry(QtCore.QRect(340, 560, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label_31.setGeometry(QtCore.QRect(120, 500, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.label_70 = QtWidgets.QLabel(self.groupBox_4)
        self.label_70.setGeometry(QtCore.QRect(170, 30, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_70.setFont(font)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.groupBox_4)
        self.label_71.setGeometry(QtCore.QRect(350, 30, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_71.setFont(font)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.groupBox_4)
        self.label_72.setGeometry(QtCore.QRect(20, 50, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_72.sizePolicy().hasHeightForWidth())
        self.label_72.setSizePolicy(sizePolicy)
        self.label_72.setMinimumSize(QtCore.QSize(100, 100))
        self.label_72.setMaximumSize(QtCore.QSize(100, 100))
        self.label_72.setText("")
        self.label_72.setPixmap(QtGui.QPixmap("heading.png"))
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.groupBox_4)
        self.label_73.setGeometry(QtCore.QRect(190, 50, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_73.sizePolicy().hasHeightForWidth())
        self.label_73.setSizePolicy(sizePolicy)
        self.label_73.setText("")
        self.label_73.setPixmap(QtGui.QPixmap("roll.png"))
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.groupBox_4)
        self.label_74.setGeometry(QtCore.QRect(360, 50, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_74.sizePolicy().hasHeightForWidth())
        self.label_74.setSizePolicy(sizePolicy)
        self.label_74.setText("")
        self.label_74.setPixmap(QtGui.QPixmap("pitch.png"))
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.groupBox_4)
        self.label_75.setGeometry(QtCore.QRect(30, 150, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_75.setFont(font)
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.groupBox_4)
        self.label_76.setGeometry(QtCore.QRect(200, 150, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_76.setFont(font)
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.groupBox_4)
        self.label_77.setGeometry(QtCore.QRect(370, 150, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_77.setFont(font)
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 390, 741, 241))
        self.groupBox_5.setObjectName("groupBox_5")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit.setGeometry(QtCore.QRect(20, 40, 721, 171))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.label_50 = QtWidgets.QLabel(self.tab)
        self.label_50.setGeometry(QtCore.QRect(160, 600, 181, 21))
        self.label_50.setStyleSheet("color:rgb(0, 0, 255)")
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.tab)
        self.label_51.setGeometry(QtCore.QRect(300, 600, 181, 21))
        self.label_51.setStyleSheet("color:rgb(255, 170, 0)")
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.tab)
        self.label_52.setGeometry(QtCore.QRect(450, 600, 181, 21))
        self.label_52.setStyleSheet("color:rgb(255, 0, 0)")
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.tab)
        self.label_53.setGeometry(QtCore.QRect(20, 600, 181, 21))
        self.label_53.setStyleSheet("color:rgb(85, 170, 0)")
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setGeometry(QtCore.QRect(390, 230, 371, 151))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_44 = QtWidgets.QLabel(self.groupBox_9)
        self.label_44.setGeometry(QtCore.QRect(40, 60, 151, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.label_48 = QtWidgets.QLabel(self.groupBox_9)
        self.label_48.setGeometry(QtCore.QRect(40, 30, 141, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_9)
        self.progressBar.setGeometry(QtCore.QRect(230, 30, 118, 23))
        self.progressBar.setMinimum(1400)
        self.progressBar.setMaximum(2500)
        self.progressBar.setProperty("value", 1500)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox_9)
        self.progressBar_2.setGeometry(QtCore.QRect(230, 60, 118, 23))
        self.progressBar_2.setMinimum(1400)
        self.progressBar_2.setMaximum(2500)
        self.progressBar_2.setProperty("value", 1500)
        self.progressBar_2.setObjectName("progressBar_2")
        self.label_79 = QtWidgets.QLabel(self.tab)
        self.label_79.setGeometry(QtCore.QRect(590, 600, 181, 21))
        self.label_79.setStyleSheet("color:rgb(170, 0, 0)")
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.groupBox_4.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_5.raise_()
        self.label_50.raise_()
        self.label_51.raise_()
        self.label_52.raise_()
        self.label_53.raise_()
        self.groupBox_9.raise_()
        self.label_79.raise_()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/noun_dashboard_357677.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 60, 441, 171))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_38 = QtWidgets.QLabel(self.groupBox_6)
        self.label_38.setGeometry(QtCore.QRect(10, 40, 181, 21))
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_6)
        self.label_39.setGeometry(QtCore.QRect(10, 70, 181, 21))
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_6)
        self.label_40.setGeometry(QtCore.QRect(10, 100, 181, 21))
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupBox_6)
        self.label_41.setGeometry(QtCore.QRect(230, 40, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color:rgb(255, 0, 0)")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox.setGeometry(QtCore.QRect(230, 100, 181, 27))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_2.setGeometry(QtCore.QRect(230, 70, 181, 27))
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton.setGeometry(QtCore.QRect(230, 130, 181, 27))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_7.setEnabled(True)
        self.pushButton_7.setGeometry(QtCore.QRect(40, 130, 121, 27))
        self.pushButton_7.setObjectName("pushButton_7")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 250, 441, 131))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_42 = QtWidgets.QLabel(self.groupBox_7)
        self.label_42.setGeometry(QtCore.QRect(10, 40, 181, 21))
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.groupBox_7)
        self.label_43.setGeometry(QtCore.QRect(10, 70, 181, 21))
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.label_45 = QtWidgets.QLabel(self.groupBox_7)
        self.label_45.setGeometry(QtCore.QRect(230, 40, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color:rgb(255, 0, 0)")
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_4.setGeometry(QtCore.QRect(230, 70, 181, 27))
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setObjectName("comboBox_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 100, 181, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_8.setGeometry(QtCore.QRect(40, 100, 121, 27))
        self.pushButton_8.setObjectName("pushButton_8")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 410, 441, 171))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_46 = QtWidgets.QLabel(self.groupBox_8)
        self.label_46.setGeometry(QtCore.QRect(10, 40, 201, 21))
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.groupBox_8)
        self.label_47.setGeometry(QtCore.QRect(10, 70, 181, 21))
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_49 = QtWidgets.QLabel(self.groupBox_8)
        self.label_49.setGeometry(QtCore.QRect(230, 40, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("color:rgb(255, 0, 0)")
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_8)
        self.comboBox_6.setGeometry(QtCore.QRect(230, 70, 181, 27))
        self.comboBox_6.setEditable(True)
        self.comboBox_6.setObjectName("comboBox_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 100, 181, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_9.setGeometry(QtCore.QRect(40, 100, 121, 27))
        self.pushButton_9.setObjectName("pushButton_9")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_16.setGeometry(QtCore.QRect(650, 90, 441, 131))
        self.groupBox_16.setObjectName("groupBox_16")
        self.label_114 = QtWidgets.QLabel(self.groupBox_16)
        self.label_114.setGeometry(QtCore.QRect(10, 40, 181, 21))
        self.label_114.setAlignment(QtCore.Qt.AlignCenter)
        self.label_114.setObjectName("label_114")
        self.label_115 = QtWidgets.QLabel(self.groupBox_16)
        self.label_115.setGeometry(QtCore.QRect(10, 70, 181, 21))
        self.label_115.setAlignment(QtCore.Qt.AlignCenter)
        self.label_115.setObjectName("label_115")
        self.label_116 = QtWidgets.QLabel(self.groupBox_16)
        self.label_116.setGeometry(QtCore.QRect(230, 40, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_116.setFont(font)
        self.label_116.setStyleSheet("color:rgb(255, 0, 0)")
        self.label_116.setAlignment(QtCore.Qt.AlignCenter)
        self.label_116.setObjectName("label_116")
        self.comboBox_11 = QtWidgets.QComboBox(self.groupBox_16)
        self.comboBox_11.setGeometry(QtCore.QRect(230, 70, 181, 27))
        self.comboBox_11.setEditable(True)
        self.comboBox_11.setObjectName("comboBox_11")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_18.setGeometry(QtCore.QRect(230, 100, 181, 27))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_19.setGeometry(QtCore.QRect(40, 100, 121, 27))
        self.pushButton_19.setObjectName("pushButton_19")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_17.setGeometry(QtCore.QRect(650, 240, 441, 131))
        self.groupBox_17.setObjectName("groupBox_17")
        self.label_122 = QtWidgets.QLabel(self.groupBox_17)
        self.label_122.setGeometry(QtCore.QRect(10, 40, 181, 21))
        self.label_122.setAlignment(QtCore.Qt.AlignCenter)
        self.label_122.setObjectName("label_122")
        self.label_123 = QtWidgets.QLabel(self.groupBox_17)
        self.label_123.setGeometry(QtCore.QRect(10, 70, 181, 21))
        self.label_123.setAlignment(QtCore.Qt.AlignCenter)
        self.label_123.setObjectName("label_123")
        self.label_124 = QtWidgets.QLabel(self.groupBox_17)
        self.label_124.setGeometry(QtCore.QRect(230, 40, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_124.setFont(font)
        self.label_124.setStyleSheet("color:rgb(255, 0, 0)")
        self.label_124.setAlignment(QtCore.Qt.AlignCenter)
        self.label_124.setObjectName("label_124")
        self.comboBox_13 = QtWidgets.QComboBox(self.groupBox_17)
        self.comboBox_13.setGeometry(QtCore.QRect(230, 70, 181, 27))
        self.comboBox_13.setEditable(True)
        self.comboBox_13.setObjectName("comboBox_13")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_17)
        self.pushButton_22.setGeometry(QtCore.QRect(230, 100, 181, 27))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_17)
        self.pushButton_23.setGeometry(QtCore.QRect(40, 100, 121, 27))
        self.pushButton_23.setObjectName("pushButton_23")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_18.setGeometry(QtCore.QRect(650, 400, 441, 131))
        self.groupBox_18.setObjectName("groupBox_18")
        self.label_125 = QtWidgets.QLabel(self.groupBox_18)
        self.label_125.setGeometry(QtCore.QRect(10, 40, 181, 21))
        self.label_125.setAlignment(QtCore.Qt.AlignCenter)
        self.label_125.setObjectName("label_125")
        self.label_126 = QtWidgets.QLabel(self.groupBox_18)
        self.label_126.setGeometry(QtCore.QRect(10, 70, 181, 21))
        self.label_126.setAlignment(QtCore.Qt.AlignCenter)
        self.label_126.setObjectName("label_126")
        self.label_127 = QtWidgets.QLabel(self.groupBox_18)
        self.label_127.setGeometry(QtCore.QRect(230, 40, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_127.setFont(font)
        self.label_127.setStyleSheet("color:rgb(255, 0, 0)")
        self.label_127.setAlignment(QtCore.Qt.AlignCenter)
        self.label_127.setObjectName("label_127")
        self.comboBox_14 = QtWidgets.QComboBox(self.groupBox_18)
        self.comboBox_14.setGeometry(QtCore.QRect(230, 70, 181, 27))
        self.comboBox_14.setEditable(True)
        self.comboBox_14.setObjectName("comboBox_14")
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_18)
        self.pushButton_24.setGeometry(QtCore.QRect(230, 100, 181, 27))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_18)
        self.pushButton_25.setGeometry(QtCore.QRect(40, 100, 121, 27))
        self.pushButton_25.setObjectName("pushButton_25")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/noun_connection_1583671.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.graphicsView_3 = QOSM(self.tab_3)
        self.graphicsView_3.setGeometry(QtCore.QRect(10, 10, 1251, 621))
        self.graphicsView_3.setObjectName("graphicsView_3")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/noun_Map_972135.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.graphicsView_6 = PlotWidget(self.tab_4)
        self.graphicsView_6.setGeometry(QtCore.QRect(40, 471, 581, 141))
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.graphicsView_7 = PlotWidget(self.tab_4)
        self.graphicsView_7.setGeometry(QtCore.QRect(40, 260, 581, 141))
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.graphicsView_8 = PlotWidget(self.tab_4)
        self.graphicsView_8.setGeometry(QtCore.QRect(40, 60, 581, 141))
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.graphicsView_9 = PlotWidget(self.tab_4)
        self.graphicsView_9.setGeometry(QtCore.QRect(650, 59, 581, 141))
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.graphicsView_11 = PlotWidget(self.tab_4)
        self.graphicsView_11.setGeometry(QtCore.QRect(650, 470, 581, 141))
        self.graphicsView_11.setObjectName("graphicsView_11")
        self.label_32 = QtWidgets.QLabel(self.tab_4)
        self.label_32.setGeometry(QtCore.QRect(40, 40, 581, 20))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_4)
        self.label_33.setGeometry(QtCore.QRect(650, 40, 581, 17))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_4)
        self.label_34.setGeometry(QtCore.QRect(40, 240, 581, 20))
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(self.tab_4)
        self.label_36.setGeometry(QtCore.QRect(40, 450, 581, 20))
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_4)
        self.label_37.setGeometry(QtCore.QRect(650, 450, 581, 17))
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.graphicsView_10 = PlotWidget(self.tab_4)
        self.graphicsView_10.setGeometry(QtCore.QRect(650, 259, 581, 141))
        self.graphicsView_10.setObjectName("graphicsView_10")
        self.label_35 = QtWidgets.QLabel(self.tab_4)
        self.label_35.setGeometry(QtCore.QRect(650, 240, 581, 17))
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/noun_Graph_1495300.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 30, 481, 241))
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalSlider = QtWidgets.QSlider(self.groupBox_10)
        self.verticalSlider.setGeometry(QtCore.QRect(80, 60, 29, 171))
        self.verticalSlider.setMaximum(3)
        self.verticalSlider.setPageStep(1)
        self.verticalSlider.setSliderPosition(0)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setInvertedAppearance(False)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label_60 = QtWidgets.QLabel(self.groupBox_10)
        self.label_60.setGeometry(QtCore.QRect(120, 161, 131, 17))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.groupBox_10)
        self.label_61.setGeometry(QtCore.QRect(120, 111, 131, 17))
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.groupBox_10)
        self.label_62.setGeometry(QtCore.QRect(120, 61, 161, 17))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.groupBox_10)
        self.label_63.setGeometry(QtCore.QRect(120, 210, 161, 17))
        self.label_63.setObjectName("label_63")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_4.setGeometry(QtCore.QRect(370, 60, 99, 27))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_64 = QtWidgets.QLabel(self.groupBox_10)
        self.label_64.setGeometry(QtCore.QRect(270, 110, 91, 20))
        self.label_64.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.groupBox_10)
        self.label_65.setGeometry(QtCore.QRect(260, 160, 101, 20))
        self.label_65.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_65.setObjectName("label_65")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox.setGeometry(QtCore.QRect(368, 110, 101, 27))
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox.setProperty("value", 3.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(370, 160, 101, 27))
        self.doubleSpinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_2.setProperty("value", 5.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.label_90 = QtWidgets.QLabel(self.groupBox_10)
        self.label_90.setGeometry(QtCore.QRect(0, 40, 81, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_90.setFont(font)
        self.label_90.setAlignment(QtCore.Qt.AlignCenter)
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.groupBox_10)
        self.label_91.setGeometry(QtCore.QRect(10, 60, 71, 17))
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(self.groupBox_10)
        self.label_92.setGeometry(QtCore.QRect(10, 110, 71, 17))
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName("label_92")
        self.label_95 = QtWidgets.QLabel(self.groupBox_10)
        self.label_95.setGeometry(QtCore.QRect(10, 160, 71, 17))
        self.label_95.setAlignment(QtCore.Qt.AlignCenter)
        self.label_95.setObjectName("label_95")
        self.label_96 = QtWidgets.QLabel(self.groupBox_10)
        self.label_96.setGeometry(QtCore.QRect(10, 210, 71, 20))
        self.label_96.setAlignment(QtCore.Qt.AlignCenter)
        self.label_96.setObjectName("label_96")
        self.label_97 = QtWidgets.QLabel(self.groupBox_10)
        self.label_97.setGeometry(QtCore.QRect(120, 40, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_97.setFont(font)
        self.label_97.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_97.setObjectName("label_97")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_11.setGeometry(QtCore.QRect(520, 30, 151, 241))
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_59 = QtWidgets.QLabel(self.groupBox_11)
        self.label_59.setGeometry(QtCore.QRect(30, 190, 31, 17))
        self.label_59.setObjectName("label_59")
        self.label_58 = QtWidgets.QLabel(self.groupBox_11)
        self.label_58.setGeometry(QtCore.QRect(20, 140, 111, 17))
        self.label_58.setObjectName("label_58")
        self.label_55 = QtWidgets.QLabel(self.groupBox_11)
        self.label_55.setGeometry(QtCore.QRect(80, 100, 31, 17))
        self.label_55.setObjectName("label_55")
        self.label_57 = QtWidgets.QLabel(self.groupBox_11)
        self.label_57.setGeometry(QtCore.QRect(80, 190, 31, 17))
        self.label_57.setObjectName("label_57")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox_11)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(30, 160, 71, 29))
        self.horizontalSlider_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.horizontalSlider_2.setMaximum(1)
        self.horizontalSlider_2.setPageStep(1)
        self.horizontalSlider_2.setProperty("value", 1)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_56 = QtWidgets.QLabel(self.groupBox_11)
        self.label_56.setGeometry(QtCore.QRect(20, 50, 111, 17))
        self.label_56.setObjectName("label_56")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_11)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 70, 71, 29))
        self.horizontalSlider.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.horizontalSlider.setMaximum(1)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setProperty("value", 1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_54 = QtWidgets.QLabel(self.groupBox_11)
        self.label_54.setGeometry(QtCore.QRect(30, 100, 31, 17))
        self.label_54.setObjectName("label_54")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_12.setGeometry(QtCore.QRect(680, 30, 581, 591))
        self.groupBox_12.setObjectName("groupBox_12")
        self.graphicsView_13 = PlotWidget(self.groupBox_12)
        self.graphicsView_13.setGeometry(QtCore.QRect(30, 40, 541, 541))
        self.graphicsView_13.setObjectName("graphicsView_13")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 370, 681, 251))
        self.groupBox_13.setObjectName("groupBox_13")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_13)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 30, 641, 201))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_66 = QtWidgets.QLabel(self.groupBox_13)
        self.label_66.setGeometry(QtCore.QRect(100, 230, 181, 21))
        self.label_66.setStyleSheet("color:rgb(0, 0, 255)")
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.groupBox_13)
        self.label_67.setGeometry(QtCore.QRect(-30, 230, 181, 21))
        self.label_67.setStyleSheet("color:rgb(85, 170, 0)")
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.label_80 = QtWidgets.QLabel(self.groupBox_13)
        self.label_80.setGeometry(QtCore.QRect(510, 230, 181, 21))
        self.label_80.setStyleSheet("color:rgb(170, 0, 0)")
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.label_68 = QtWidgets.QLabel(self.groupBox_13)
        self.label_68.setGeometry(QtCore.QRect(240, 230, 181, 21))
        self.label_68.setStyleSheet("color:rgb(255, 170, 0)")
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.groupBox_13)
        self.label_69.setGeometry(QtCore.QRect(380, 230, 181, 21))
        self.label_69.setStyleSheet("color:rgb(255, 0, 0)")
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setGeometry(QtCore.QRect(160, 280, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color:rgb(0, 170, 0)")
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setChecked(False)
        self.pushButton_5.setAutoRepeat(False)
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_6.setGeometry(QtCore.QRect(330, 280, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("color:rgb(255, 0, 0)")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_78 = QtWidgets.QLabel(self.tab_5)
        self.label_78.setGeometry(QtCore.QRect(710, 610, 541, 20))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_78.setFont(font)
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/noun_sequence_121702.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_5, icon5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_14.setGeometry(QtCore.QRect(20, 30, 611, 151))
        self.groupBox_14.setObjectName("groupBox_14")
        self.label_81 = QtWidgets.QLabel(self.groupBox_14)
        self.label_81.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(90, 50, 111, 27))
        self.doubleSpinBox_3.setDecimals(4)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(90, 80, 111, 27))
        self.doubleSpinBox_4.setDecimals(4)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(90, 110, 111, 27))
        self.doubleSpinBox_5.setDecimals(4)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.label_82 = QtWidgets.QLabel(self.groupBox_14)
        self.label_82.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(self.groupBox_14)
        self.label_83.setGeometry(QtCore.QRect(10, 110, 61, 21))
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.groupBox_14)
        self.label_84.setGeometry(QtCore.QRect(310, 80, 61, 21))
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(390, 80, 111, 27))
        self.doubleSpinBox_6.setDecimals(4)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.label_85 = QtWidgets.QLabel(self.groupBox_14)
        self.label_85.setGeometry(QtCore.QRect(310, 50, 61, 21))
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(390, 110, 111, 27))
        self.doubleSpinBox_7.setDecimals(4)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.label_86 = QtWidgets.QLabel(self.groupBox_14)
        self.label_86.setGeometry(QtCore.QRect(310, 110, 61, 21))
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.groupBox_14)
        self.doubleSpinBox_8.setGeometry(QtCore.QRect(390, 50, 111, 27))
        self.doubleSpinBox_8.setDecimals(4)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.label_93 = QtWidgets.QLabel(self.groupBox_14)
        self.label_93.setGeometry(QtCore.QRect(20, 30, 181, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_93.setFont(font)
        self.label_93.setStyleSheet("")
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName("label_93")
        self.label_94 = QtWidgets.QLabel(self.groupBox_14)
        self.label_94.setGeometry(QtCore.QRect(320, 30, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_94.setFont(font)
        self.label_94.setStyleSheet("")
        self.label_94.setAlignment(QtCore.Qt.AlignCenter)
        self.label_94.setObjectName("label_94")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_15.setGeometry(QtCore.QRect(650, 30, 611, 151))
        self.groupBox_15.setObjectName("groupBox_15")
        self.label_87 = QtWidgets.QLabel(self.groupBox_15)
        self.label_87.setGeometry(QtCore.QRect(30, 80, 61, 21))
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setObjectName("label_87")
        self.label_88 = QtWidgets.QLabel(self.groupBox_15)
        self.label_88.setGeometry(QtCore.QRect(30, 110, 61, 21))
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setObjectName("label_88")
        self.label_89 = QtWidgets.QLabel(self.groupBox_15)
        self.label_89.setGeometry(QtCore.QRect(30, 50, 61, 21))
        self.label_89.setAlignment(QtCore.Qt.AlignCenter)
        self.label_89.setObjectName("label_89")
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_9.setGeometry(QtCore.QRect(110, 110, 111, 27))
        self.doubleSpinBox_9.setDecimals(4)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_10.setGeometry(QtCore.QRect(110, 80, 111, 27))
        self.doubleSpinBox_10.setDecimals(4)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.doubleSpinBox_11.setGeometry(QtCore.QRect(110, 50, 111, 27))
        self.doubleSpinBox_11.setDecimals(4)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setGeometry(QtCore.QRect(400, 590, 181, 27))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_11.setEnabled(False)
        self.pushButton_11.setGeometry(QtCore.QRect(600, 590, 181, 27))
        self.pushButton_11.setObjectName("pushButton_11")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/noun_configuration_1613324.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_6, icon6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_99 = QtWidgets.QLabel(self.tab_7)
        self.label_99.setGeometry(QtCore.QRect(70, 270, 91, 17))
        self.label_99.setObjectName("label_99")
        self.label_100 = QtWidgets.QLabel(self.tab_7)
        self.label_100.setGeometry(QtCore.QRect(70, 150, 101, 17))
        self.label_100.setObjectName("label_100")
        self.RETROCEDERZ = QtWidgets.QPushButton(self.tab_7)
        self.RETROCEDERZ.setGeometry(QtCore.QRect(70, 290, 89, 25))
        self.RETROCEDERZ.setObjectName("RETROCEDERZ")
        self.label_101 = QtWidgets.QLabel(self.tab_7)
        self.label_101.setGeometry(QtCore.QRect(70, 210, 101, 17))
        self.label_101.setObjectName("label_101")
        self.RETROCEDERY = QtWidgets.QPushButton(self.tab_7)
        self.RETROCEDERY.setGeometry(QtCore.QRect(70, 230, 89, 25))
        self.RETROCEDERY.setObjectName("RETROCEDERY")
        self.Salir = QtWidgets.QPushButton(self.tab_7)
        self.Salir.setGeometry(QtCore.QRect(290, 400, 89, 25))
        self.Salir.setObjectName("Salir")
        self.PARADAY = QtWidgets.QPushButton(self.tab_7)
        self.PARADAY.setGeometry(QtCore.QRect(180, 230, 89, 25))
        self.PARADAY.setObjectName("PARADAY")
        self.AVANZARZ = QtWidgets.QPushButton(self.tab_7)
        self.AVANZARZ.setGeometry(QtCore.QRect(290, 290, 89, 25))
        self.AVANZARZ.setObjectName("AVANZARZ")
        self.RETROCEDERX = QtWidgets.QPushButton(self.tab_7)
        self.RETROCEDERX.setGeometry(QtCore.QRect(70, 170, 89, 25))
        self.RETROCEDERX.setObjectName("RETROCEDERX")
        self.AVANZARX = QtWidgets.QPushButton(self.tab_7)
        self.AVANZARX.setGeometry(QtCore.QRect(290, 170, 89, 25))
        self.AVANZARX.setObjectName("AVANZARX")
        self.AVANZARY = QtWidgets.QPushButton(self.tab_7)
        self.AVANZARY.setGeometry(QtCore.QRect(290, 230, 89, 25))
        self.AVANZARY.setObjectName("AVANZARY")
        self.PARADAZ = QtWidgets.QPushButton(self.tab_7)
        self.PARADAZ.setGeometry(QtCore.QRect(180, 290, 89, 25))
        self.PARADAZ.setObjectName("PARADAZ")
        self.PARADAX = QtWidgets.QPushButton(self.tab_7)
        self.PARADAX.setGeometry(QtCore.QRect(180, 170, 89, 25))
        self.PARADAX.setObjectName("PARADAX")
        self.label_103 = QtWidgets.QLabel(self.tab_7)
        self.label_103.setEnabled(True)
        self.label_103.setGeometry(QtCore.QRect(400, 70, 851, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_103.sizePolicy().hasHeightForWidth())
        self.label_103.setSizePolicy(sizePolicy)
        self.label_103.setAutoFillBackground(False)
        self.label_103.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_103.setText("")
        self.label_103.setPixmap(QtGui.QPixmap("ceres.png"))
        self.label_103.setScaledContents(True)
        self.label_103.setAlignment(QtCore.Qt.AlignCenter)
        self.label_103.setObjectName("label_103")
        self.tabWidget.addTab(self.tab_7, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1280, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuCeres_GUI = QtWidgets.QMenu(self.menuBar)
        self.menuCeres_GUI.setObjectName("menuCeres_GUI")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuCeres_GUI.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuCeres_GUI.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CERES GUI"))
        self.groupBox.setTitle(_translate("MainWindow", "RC Channels Overview"))
        self.label.setText(_translate("MainWindow", "Throttle"))
        self.progressBarYaw.setFormat(_translate("MainWindow", "%v%"))
        self.label_2.setText(_translate("MainWindow", "Yaw Speed"))
        self.label_3.setText(_translate("MainWindow", "AUX"))
        self.label_4.setText(_translate("MainWindow", "Emergency"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Connexions Overview"))
        self.label_5.setText(_translate("MainWindow", "IMU Connexion"))
        self.label_6.setText(_translate("MainWindow", "Arduino RC Connexion"))
        self.label_7.setText(_translate("MainWindow", "Main Arduino Connexion"))
        self.label_8.setText(_translate("MainWindow", "Not Connected"))
        self.label_9.setText(_translate("MainWindow", "Not Connected"))
        self.label_10.setText(_translate("MainWindow", "Not Connected"))
        self.label_117.setText(_translate("MainWindow", "Not Connected"))
        self.label_118.setText(_translate("MainWindow", "Arduino Actuador X"))
        self.label_128.setText(_translate("MainWindow", "Arduino Actuador Y"))
        self.label_130.setText(_translate("MainWindow", "Not Connected"))
        self.label_129.setText(_translate("MainWindow", "Arduino Actuador Z"))
        self.label_131.setText(_translate("MainWindow", "Not Connected"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Robot Status"))
        self.label_11.setText(_translate("MainWindow", "Mode"))
        self.label_12.setText(_translate("MainWindow", "Emergency Stop"))
        self.label_13.setText(_translate("MainWindow", "Drivers Brakes"))
        self.label_14.setText(_translate("MainWindow", "EM Brakes"))
        self.label_23.setText(_translate("MainWindow", "Cooling Pumps"))
        self.label_24.setText(_translate("MainWindow", "Desactivated"))
        self.label_25.setText(_translate("MainWindow", "Desactivated"))
        self.label_26.setText(_translate("MainWindow", "Desactivated"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Robot Position"))
        self.label_15.setText(_translate("MainWindow", "Heading"))
        self.label_16.setText(_translate("MainWindow", "Map Position"))
        self.label_17.setText(_translate("MainWindow", "Latitude:"))
        self.label_18.setText(_translate("MainWindow", "Longitude: "))
        self.label_19.setText(_translate("MainWindow", "Position to Origin:"))
        self.label_20.setText(_translate("MainWindow", "Northing:"))
        self.label_21.setText(_translate("MainWindow", "Easting:"))
        self.label_22.setText(_translate("MainWindow", "Altitude:"))
        self.label_27.setText(_translate("MainWindow", "48.856614"))
        self.label_28.setText(_translate("MainWindow", "2.3522219"))
        self.label_29.setText(_translate("MainWindow", "15.65m"))
        self.label_30.setText(_translate("MainWindow", "172.6m"))
        self.label_31.setText(_translate("MainWindow", "2300m"))
        self.label_70.setText(_translate("MainWindow", "Roll"))
        self.label_71.setText(_translate("MainWindow", "Pitch"))
        self.label_75.setText(_translate("MainWindow", "180°"))
        self.label_76.setText(_translate("MainWindow", "180°"))
        self.label_77.setText(_translate("MainWindow", "180°"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Terminal Messages"))
        self.label_50.setText(_translate("MainWindow", "Info Messages"))
        self.label_51.setText(_translate("MainWindow", "Warning Messages"))
        self.label_52.setText(_translate("MainWindow", "Error Messages"))
        self.label_53.setText(_translate("MainWindow", "Debug Messages"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Drivers Overview"))
        self.label_44.setText(_translate("MainWindow", "Right Driver Voltage"))
        self.label_48.setText(_translate("MainWindow", "Left Driver Voltage"))
        self.progressBar.setFormat(_translate("MainWindow", "%v mV"))
        self.progressBar_2.setFormat(_translate("MainWindow", "%v mV"))
        self.label_79.setText(_translate("MainWindow", "Fatal Messages"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Robot Overview"))
        self.groupBox_6.setTitle(_translate("MainWindow", "IMU"))
        self.label_38.setText(_translate("MainWindow", "IMU Connexion"))
        self.label_39.setText(_translate("MainWindow", "Serial Port"))
        self.label_40.setText(_translate("MainWindow", "Serial Velocity"))
        self.label_41.setText(_translate("MainWindow", "Not Connected"))
        self.comboBox.setItemText(0, _translate("MainWindow", "115200"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1200"))
        self.comboBox.setItemText(2, _translate("MainWindow", "2400"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4800"))
        self.comboBox.setItemText(4, _translate("MainWindow", "9600"))
        self.comboBox.setItemText(5, _translate("MainWindow", "19200"))
        self.comboBox.setItemText(6, _translate("MainWindow", "38400"))
        self.comboBox.setItemText(7, _translate("MainWindow", "57600"))
        self.comboBox.setItemText(8, _translate("MainWindow", "230400"))
        self.comboBox.setItemText(9, _translate("MainWindow", "250000"))
        self.comboBox.setItemText(10, _translate("MainWindow", "460800"))
        self.comboBox.setItemText(11, _translate("MainWindow", "500000"))
        self.comboBox.setItemText(12, _translate("MainWindow", "800000"))
        self.comboBox.setItemText(13, _translate("MainWindow", "921600"))
        self.comboBox.setItemText(14, _translate("MainWindow", "1000000"))
        self.comboBox.setItemText(15, _translate("MainWindow", "2000000"))
        self.pushButton.setText(_translate("MainWindow", "Connect"))
        self.pushButton_7.setText(_translate("MainWindow", "Auto-Detect"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Arduino RC"))
        self.label_42.setText(_translate("MainWindow", "Arduino RC Connexion"))
        self.label_43.setText(_translate("MainWindow", "Serial Port"))
        self.label_45.setText(_translate("MainWindow", "Not Connected"))
        self.pushButton_2.setText(_translate("MainWindow", "Connect"))
        self.pushButton_8.setText(_translate("MainWindow", "Auto-Detect"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Main Arduino"))
        self.label_46.setText(_translate("MainWindow", "Main Arduino Connexion"))
        self.label_47.setText(_translate("MainWindow", "Serial Port"))
        self.label_49.setText(_translate("MainWindow", "Not Connected"))
        self.pushButton_3.setText(_translate("MainWindow", "Connect"))
        self.pushButton_9.setText(_translate("MainWindow", "Auto-Detect"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Actuador X"))
        self.label_114.setText(_translate("MainWindow", "Act. X Connexion"))
        self.label_115.setText(_translate("MainWindow", "Serial Port"))
        self.label_116.setText(_translate("MainWindow", "Not Connected"))
        self.pushButton_18.setText(_translate("MainWindow", "Connect"))
        self.pushButton_19.setText(_translate("MainWindow", "Auto-Detect"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Actuador Y"))
        self.label_122.setText(_translate("MainWindow", "Act. Y Connexion"))
        self.label_123.setText(_translate("MainWindow", "Serial Port"))
        self.label_124.setText(_translate("MainWindow", "Not Connected"))
        self.pushButton_22.setText(_translate("MainWindow", "Connect"))
        self.pushButton_23.setText(_translate("MainWindow", "Auto-Detect"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Actuador Z"))
        self.label_125.setText(_translate("MainWindow", "Act. Z Connexion"))
        self.label_126.setText(_translate("MainWindow", "Serial Port"))
        self.label_127.setText(_translate("MainWindow", "Not Connected"))
        self.pushButton_24.setText(_translate("MainWindow", "Connect"))
        self.pushButton_25.setText(_translate("MainWindow", "Auto-Detect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Connections"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "GPS / Map"))
        self.label_32.setText(_translate("MainWindow", "Easting Position [m]"))
        self.label_33.setText(_translate("MainWindow", "Robot X Velocity [m/s]"))
        self.label_34.setText(_translate("MainWindow", "Northing Position [m]"))
        self.label_36.setText(_translate("MainWindow", "Heading Orientation [deg]"))
        self.label_37.setText(_translate("MainWindow", "Robot Angular Velocity [rad/s]"))
        self.label_35.setText(_translate("MainWindow", "Robot Y Velocity [m/s]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Sensors"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Trajectory Options"))
        self.label_60.setText(_translate("MainWindow", "Circular Trajectory"))
        self.label_61.setText(_translate("MainWindow", "Linear Trajectory"))
        self.label_62.setText(_translate("MainWindow", "Custom CSV Trajectory"))
        self.label_63.setText(_translate("MainWindow", "Manual Trajectory"))
        self.pushButton_4.setText(_translate("MainWindow", "Open File..."))
        self.label_64.setText(_translate("MainWindow", "Distance [m]:"))
        self.label_65.setText(_translate("MainWindow", "Diameter [m]:"))
        self.label_90.setText(_translate("MainWindow", "Controller"))
        self.label_91.setText(_translate("MainWindow", "Pose"))
        self.label_92.setText(_translate("MainWindow", "Vel"))
        self.label_95.setText(_translate("MainWindow", "Vel"))
        self.label_96.setText(_translate("MainWindow", "Custom"))
        self.label_97.setText(_translate("MainWindow", "Trajectory Selection"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Recording Options"))
        self.label_59.setText(_translate("MainWindow", "ON"))
        self.label_58.setText(_translate("MainWindow", "BAG Recording"))
        self.label_55.setText(_translate("MainWindow", "OFF"))
        self.label_57.setText(_translate("MainWindow", "OFF"))
        self.label_56.setText(_translate("MainWindow", "CSV Recording"))
        self.label_54.setText(_translate("MainWindow", "ON"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Movement Previews"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Terminal Messages"))
        self.label_66.setText(_translate("MainWindow", "Info Messages"))
        self.label_67.setText(_translate("MainWindow", "Debug Messages"))
        self.label_80.setText(_translate("MainWindow", "Fatal Messages"))
        self.label_68.setText(_translate("MainWindow", "Warning Messages"))
        self.label_69.setText(_translate("MainWindow", "Error Messages"))
        self.pushButton_5.setText(_translate("MainWindow", "START"))
        self.pushButton_6.setText(_translate("MainWindow", "STOP"))
        self.label_78.setText(_translate("MainWindow", "Representation in the CERES Referential: X=Right, Y=Front"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Test Sequences"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Low-Level Speed Controller (PID)"))
        self.label_81.setText(_translate("MainWindow", "Kp"))
        self.label_82.setText(_translate("MainWindow", "Ki"))
        self.label_83.setText(_translate("MainWindow", "Kd"))
        self.label_84.setText(_translate("MainWindow", "Ki"))
        self.label_85.setText(_translate("MainWindow", "Kp"))
        self.label_86.setText(_translate("MainWindow", "Kd"))
        self.label_93.setText(_translate("MainWindow", "Linear Speed U [m/s]"))
        self.label_94.setText(_translate("MainWindow", "Rotational Speed W [rad/s]"))
        self.groupBox_15.setTitle(_translate("MainWindow", "High-Level Position Controller"))
        self.label_87.setText(_translate("MainWindow", "Ki"))
        self.label_88.setText(_translate("MainWindow", "Kd"))
        self.label_89.setText(_translate("MainWindow", "Kp"))
        self.pushButton_10.setText(_translate("MainWindow", "Read Values"))
        self.pushButton_11.setText(_translate("MainWindow", "Write Values"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Configuration"))
        self.label_99.setText(_translate("MainWindow", "Actuador Z"))
        self.label_100.setText(_translate("MainWindow", "Actuador X"))
        self.RETROCEDERZ.setText(_translate("MainWindow", "<--"))
        self.label_101.setText(_translate("MainWindow", "Actuador Y"))
        self.RETROCEDERY.setText(_translate("MainWindow", "<--"))
        self.Salir.setText(_translate("MainWindow", "Salir"))
        self.PARADAY.setText(_translate("MainWindow", "STOP"))
        self.AVANZARZ.setText(_translate("MainWindow", "-->"))
        self.RETROCEDERX.setText(_translate("MainWindow", "<--"))
        self.AVANZARX.setText(_translate("MainWindow", "-->"))
        self.AVANZARY.setText(_translate("MainWindow", "-->"))
        self.PARADAZ.setText(_translate("MainWindow", "STOP"))
        self.PARADAX.setText(_translate("MainWindow", "STOP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Actuadores"))
        self.menuCeres_GUI.setTitle(_translate("MainWindow", "Ceres GUI"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
from pyqtgraph import PlotWidget
from qOSM.common import QOSM
import ressources_rc
